language: c
compiler:
  - gcc

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "M49o2r+Y4Ei0IeF9VX9G6SDyGmqXZrepoKNPgQZte1ZCjTzrAZD/6gxbIarxzisDbsL72xB2CvvT78+EfBzV5Fc5tuj3VC87/aOvDNjnJ4UJqdc1DIbZgMsfRt7QgZXEXMlewac74Aix6b2lQkMp8RmKs6cBZDf8Mq1IA1tqbAi7EiMyWkIBEC/DuT1+s2PrzZF5BXgZGnrDDEpuwnXtkBeq2t/QCWQgfUnLcttxdaoPBDFY0XpcVm/05py3QtOoW0ZVENMPERSo+/pVRI2ixRDjsU93HD68+aJk4X2nbf9YLuC4zPMBZMMddsxvfxocSn3wOBnGLIkFkALRH3HO+c0hShApGCGUUMTrprCPYLiM15DmsR3JC+GzOW3nt8wzfvTFoIoFI2F0qw/3E+nIopLCQczUz4lFADQQZxo7e2ofIg/yCOlKJa6xl92f3IRyyEcYz7C2o4tC4WfdJ0i3RyySDqJVidPdHI5zv2jaBvFQZWAcsjszmq+0WDV7T7Fr1/J5OJhdxWgxwe/jNPvafO9jnrPlv4XziV3rIcBVuo42HkL0F3Hwm0Z/YzXSldkhZMdTwyRtKUh6IF8ZQaFWtiMUC/nMYri55qUS5toJCKQUC0RloZxLSU9f7HUaq3OPgoE0+B6v/vtF6mJ7TsQp9FV1rOar86xYILXjPndcO1Y="
before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "ksripathi/MyHelloWorld"
      description: "Your project description here"
    notification_email: kammari.sripathi@gmail.com
    build_command_prepend: "./configure"
    build_command: "make -j2"
    branch_pattern: master
    
script:
  - make -j2   



